version: "3.9"
services:
  helpserver:
    build: .
    ports:
      - "3000:3000"
    links:
      - helpmongo
  helpmongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password

